travis:
  secure:
    BINSTAR_TOKEN: YLf03h85rdSYdLAQYHJMsMpanJu1n5NL5ycoZ78pND2HhwRgLz8apg7T2RG+3SeXicwkBMQBE+qXYP9YxmIrhXC7ySMaj5V21rSK71bo1GRVQXlAhKGcCVfXAPM8qrQE0k4K+YNltkYb5Rd58POEujad4vTaSikOj/Y4lzPEQRKLjL3qUDW6n1esYv2K9gr+jwBal6p5AxLL4aR8ns3iyWiNd4ZFXx0SnH829OYVwUcG6t9qihajEejI3K0s+k/neMqdd4GVNWzHxXhP3Twz2Ll5wYZRMYqUv3qpZdYq/BGxhV5Ak/8gjjNuP0SLOPbbc6t++PvwOXRh0fh2DKcqXVwGvmb6EosCSvGQ/GNxmsYcbjdns/7CaLAzVBWnNty8mVnH2lzVIi8oLf84GFps3psurxnSqEWHx9YsRFZNOr0UAXHv7TgTPspt/IQCefJxcfsZ5TFeGX7ZbKoTNyDEb0pJgWJBM4MDaleffgCxsSstNAWmYbFL+OjOY407KiYKsfb6EgTb0s5aaxTIZ3Fvho/BiVswDBFeqQCdoDlktmDI7o0gLdjGd+fwlPyUJmXpU0p970zcvYaUfYrv1EhqD926r41SVsIfu5R68aEIpV2UzG7UtYjHuoP3imH2aiKkGHtdhaLkqJZnLEkjj9LqejTVpnM5FnWWvCWpOVWzXjs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
